
version: '3.7'
services: 
  books:
    build: .
    ports:
      - 80:3000
    environment:
      - PORT=3000
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-example}
      - DB_NAME=${DB_NAME:-myBook}
    env_file:
      - .atlas.env