
version: '3.7'

version: '3.7'

services:
  mongodb:
    image: mongo
    restart: always
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD:-example}
      - MONGO_INITDB_DATABASE=${DB_NAME:-myBook}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USERNAME:-root}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD:-example}
    depends_on:
      - mongodb

  books:
    build: .
    ports:
      - 80:3000
    environment:
      - PORT=3000
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-example}
      - DB_NAME=${DB_NAME:-myBook}
      - DB_HOST=mongodb://mongodb:27017
    depends_on:
      - mongodb
      